### ISSUE TITLE
Update the example to the WireMock module for Testcontainers

### ISSUE THREAD

**Issue by oleg-nenashev** [rogervinas/wiremock-testing#8]
Hello @rogervinas, thanks for the great overview! I used it once for the demo in April, and then I also implemented a Testcontainers Java module https://github.com/wiremock/wiremock-testcontainers-java . I wonder whether you would be interested in updating the demo to use this module, and ofc I will be happy to reference the demo from the documentation

**Comment by rogervinas** [comment]
Hi @oleg-nenashev, yes happy to update it! Thanks for the tip!

**Comment by rogervinas** [comment]
Hi @oleg-nenashev I think it works https://github.com/rogervinas/wiremock-testing/pull/24
